name:                bookshelf
version:             0.1.0.0
github:              "yusent/habitica-programming-challenges/2020-08-bookshelf"
license:             MIT
author:              "Yusent Chig"
maintainer:          "yusent@protonmail.com"
copyright:           "2020 Yusent Chig"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yusent/habitica-programming-challenges/tree/master/2020-08-bookshelf>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bookshelf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookshelf
    - strict

tests:
  bookshelf-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bookshelf
    - hspec >=2.0.0
